env: "local"

db:
  username: "postgres"
  host: "pgsql"
  port: "5432"
  dbname: "postgres"
  sslmode: "disable"

http_server:
  server_port: "0.0.0.0:8020"
  timeout: 4s
  idle_timeout: 60s

token:
  access_tokenTTL: 15m
  refresh_tokenTTL: 43200m